### ISSUE TITLE
建议新增 3s自动刷新

### ISSUE THREAD

**Issue by ghost** [AppleIdLoginHelper/AppleIdLoginHelper#1]
网页需要手动刷新才能看到新的验证码，如果能自动刷新网页就更好了

**Comment by 4kercc** [comment]
编辑文件：
`/app/view/index.html`
在第四行:
`<head>`
下面增加：
`<meta http-equiv="refresh" content="3">`
即可。

**Comment by ghost** [comment]
搞定@~

**Comment by AppleIdLoginHelper** [comment]
已加入此功能。
