### ISSUE TITLE
谁能搞个doceker出来,内个方便!

### ISSUE THREAD

**Issue by q592850** [AppleIdLoginHelper/AppleIdLoginHelper#11]
我已经搞定啦,重新编辑下,提高下知名度!我觉得这个可以搞个Docker方便点

**Comment by AppleIdLoginHelper** [comment]
确保composer install没有报错，如果有，复制到谷歌解决它

**Comment by q592850** [comment]
PHP5.6版本的支持的嘛?

**Comment by AppleIdLoginHelper** [comment]
"php": ">=7.2.5",

**Comment by q592850** [comment]
[root@mail appid.v2raytrojan.com]# composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for league/flysystem 1.1.9 -> satisfiable by league/flysystem[1.1.9].
    - league/flysystem 1.1.9 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
  Problem 2
    - Installation request for league/mime-type-detection 1.9.0 -> satisfiable by league/mime-type-detection[1.9.0].
    - league/mime-type-detection 1.9.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
  Problem 3
    - league/flysystem 1.1.9 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - topthink/framework v6.0.12 requires league/flysystem ^1.1.4 -> satisfiable by league/flysystem[1.1.9].
    - Installation request for topthink/framework v6.0.12 -> satisfiable by topthink/framework[v6.0.12].

  To enable extensions, verify that they are enabled in your .ini files:
    - /www/server/php/74/etc/php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
[root@mail appid.v2raytrojan.com]#

**Comment by q592850** [comment]
我用的是宝塔面板

**Comment by q592850** [comment]
______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 2.2.6 2022-02-04 17:00:38

**Comment by AppleIdLoginHelper** [comment]
自己搞。
