### ISSUE TITLE
验证码收着是没问题，奇怪了账户那里一直显示unknow

### ISSUE THREAD

**Issue by blackness3** [AppleIdLoginHelper/AppleIdLoginHelper#12]
验证码收着是没问题，奇怪了账户那里一直显示unkn

**Comment by q592850** [comment]
我安装了 老半天没成功,你是怎么安装成功的 可否告知下

**Comment by blackness3** [comment]
> 



> 我安装了 老半天没成功,你是怎么安装成功的 可否告知下

就按照作者写的教程

**Comment by q592850** [comment]
我再试试步骤 肯定是我哪个步骤出错了

**Comment by q592850** [comment]
[root@mail appid.v2raytrojan.com]# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - league/flysystem is locked to version 1.1.9 and an update of this package was not requested.
    - league/flysystem 1.1.9 requires ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
  Problem 2
    - league/mime-type-detection is locked to version 1.9.0 and an update of this package was not requested.
    - league/mime-type-detection 1.9.0 requires ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
  Problem 3
    - league/flysystem 1.1.9 requires ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
    - topthink/framework v6.0.12 requires league/flysystem ^1.1.4 -> satisfiable by league/flysystem[1.1.9].
    - topthink/framework is locked to version v6.0.12 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - /www/server/php/74/etc/php-cli.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-fileinfo --ignore-platform-req=ext-fileinfo --ignore-platform-req=ext-fileinfo` to temporarily ignore these required extensions.
 我每次到这步就错,您是怎么解决的???

**Comment by AppleIdLoginHelper** [comment]
> 验证码收着是没问题，奇怪了账户那里一直显示unkn

因为程序不知道验证码应该分配给哪个ios账户，你自己没配置好 `$email_correspondence`

**Comment by AppleIdLoginHelper** [comment]
> 

你php版本升级到7.2.5+了么
编辑php.ini启用fileinfo扩展
重启php
然后根目录下运行composer update
另外，域名漏了

**Comment by q592850** [comment]
无所谓 测试的

**Comment by q592850** [comment]
有TG么,能联系下么

**Comment by AppleIdLoginHelper** [comment]
> 有TG么,能联系下么

不便透露

**Comment by blackness3** [comment]
> [root@mail appid.v2raytrojan.com]# composer install Do not run Composer as root/super user! See https://getcomposer.org/root for details Continue as root/super user [yes]? yes Installing dependencies from lock file (including require-dev) Verifying lock file contents can be installed on current platform. Your lock file does not contain a compatible set of packages. Please run composer update.
> 
> Problem 1 - league/flysystem is locked to version 1.1.9 and an update of this package was not requested. - league/flysystem 1.1.9 requires ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension. Problem 2 - league/mime-type-detection is locked to version 1.9.0 and an update of this package was not requested. - league/mime-type-detection 1.9.0 requires ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension. Problem 3 - league/flysystem 1.1.9 requires ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension. - topthink/framework v6.0.12 requires league/flysystem ^1.1.4 -> satisfiable by league/flysystem[1.1.9]. - topthink/framework is locked to version v6.0.12 and an update of this package was not requested.
> 
> To enable extensions, verify that they are enabled in your .ini files: - /www/server/php/74/etc/php-cli.ini You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode. Alternatively, you can run Composer with `--ignore-platform-req=ext-fileinfo --ignore-platform-req=ext-fileinfo --ignore-platform-req=ext-fileinfo` to temporarily ignore these required extensions. 我每次到这步就错,您是怎么解决的???
运行
composer install --ignore-platform-reqs

**Comment by blackness3** [comment]
> 

确实，检查了下。打错字了 。mail写错了

**Comment by q592850** [comment]
还是报错,求助

**Comment by blackness3** [comment]
> 还是报错,求助
你升级下composer。  作者上面不是写了一些方法么，。我记得我第一次安装也报你这个错 我就用
composer install --ignore-platform-reqs。运行成功的。

**Comment by q592850** [comment]
宝塔7.8.0
PHP:7.4 扩展 fileinfo 删除禁用的 proc_open 和 putenv
Composer版本 2.2.6 2022-02-04 17:00:38
伪静态选择 thinkphp 
网站目录 /public

每次到了这不 composer install  就报错了!

**Comment by blackness3** [comment]
> 宝塔7.8.0 PHP:7.4 扩展 fileinfo 删除禁用的 proc_open 和 putenv Composer版本 2.2.6 2022-02-04 17:00:38 伪静态选择 thinkphp 网站目录 /public
> 
> 每次到了这不 composer install 就报错了!

切换成 php7.3 试试，我用的7.3.另外我没装拓展fileinfo

**Comment by AppleIdLoginHelper** [comment]
> 宝塔7.8.0 PHP:7.4 扩展 fileinfo 删除禁用的 proc_open 和 putenv Composer版本 2.2.6 2022-02-04 17:00:38 伪静态选择 thinkphp 网站目录 /public
> 
> 每次到了这不 composer install 就报错了!

重启lnmp然后composer update

**Comment by q592850** [comment]
我是宝塔nginx

**Comment by q592850** [comment]
未定义数组索引: messages
收件箱需要有至少一封包含关键词 Apple Id 的邮件。一般来说 google voice 收到的短信都会自动转发到 gmail 收件箱中
![image](https://user-images.githubusercontent.com/36805246/153743584-389a1115-364d-4aef-ad41-6acc8166f454.png)

**Comment by blackness3** [comment]
> 未定义数组索引: messages 收件箱需要有至少一封包含关键词 Apple Id 的邮件。一般来说 google voice 收到的短信都会自动转发到 gmail 收件箱中 ![image](https://user-images.githubusercontent.com/36805246/153743584-389a1115-364d-4aef-ad41-6acc8166f454.png)

在GV中 启用。吧短信转发到邮箱中。在设置里自己找找。

**Comment by q592850** [comment]
已经启用了呀

**Comment by q592850** [comment]
![image](https://user-images.githubusercontent.com/36805246/153743714-03dea44a-5407-4498-81ed-8fdeb7aa2bae.png)
你看

**Comment by q592850** [comment]
![image](https://user-images.githubusercontent.com/36805246/153743888-115a259c-5d7d-4da1-bc6c-4ee729a1d14f.png)
我 这里这样写 对么?

**Comment by AppleIdLoginHelper** [comment]
> ![image](https://user-images.githubusercontent.com/36805246/153743888-115a259c-5d7d-4da1-bc6c-4ee729a1d14f.png)
> 我 这里这样写 对么?

< id > 代表变量id，不是让你填成<123>

**Comment by blackness3** [comment]
> > ![image](https://user-images.githubusercontent.com/36805246/153743888-115a259c-5d7d-4da1-bc6c-4ee729a1d14f.png)
> > 我 这里这样写 对么?
> 
> 代表变量id，不是让你填成<123>

我想提个需求。就是查询到新验证码时，网页自动刷新，。不然每次都手动刷新才显示。

**Comment by AppleIdLoginHelper** [comment]
> > > ![image](https://user-images.githubusercontent.com/36805246/153743888-115a259c-5d7d-4da1-bc6c-4ee729a1d14f.png)
> > > 我 这里这样写 对么?
> > 
> > 
> > 代表变量id，不是让你填成<123>
> 
> 我想提个需求。就是查询到新验证码时，网页自动刷新，。不然每次都手动刷新才显示。

翻之前的issue

**Comment by q592850** [comment]
![image](https://user-images.githubusercontent.com/36805246/153744090-feda0c77-7c0b-4ed7-aa10-1899e0534eea.png)
 呀哈哈哈哈  终于踏马成功啦

**Comment by q592850** [comment]
> > > > ![图片](https://user-images.githubusercontent.com/36805246/153743888-115a259c-5d7d-4da1-bc6c-4ee729a1d14f.png)
> > > > 我这里写这样对么？
> > > 
> > > 
> > > 代表变量id，不是让你填<123>
> > 
> > 
> > 我想提个需求。码时显示，自动发现，就是现在想去网页手动搜索才发现。
> 
> 翻前的问题

怎么实现?

**Comment by q592850** [comment]
编辑文件：
/app/view/index.html
在第四行:
<head>
下面增加：
<meta http-equiv="refresh" content="3">
即可。

**Comment by q592850** [comment]
> > > ![image](https://user-images.githubusercontent.com/36805246/153743888-115a259c-5d7d-4da1-bc6c-4ee729a1d14f.png)
> > > 我 这里这样写 对么?
> > 
> > 
> > 代表变量id，不是让你填成<123>
> 
> 我想提个需求。就是查询到新验证码时，网页自动刷新，。不然每次都手动刷新才显示。
编辑文件：
/app/view/index.html
在第四行:
`<head>`
下面增加：
`<meta http-equiv="refresh" content="3">`
即可。
