### ISSUE TITLE
屏蔽icloud登录验证码

### ISSUE THREAD

**Issue by ghost** [AppleIdLoginHelper/AppleIdLoginHelper#13]
icloud.com 网站登录验证码 跟 apple.com 官网登录验证码 都会有后缀提示
现在迫切的需要 屏蔽 设备登录 icloud的验证码（可有偿）

Apple ID 代码为：171773。请勿与他人共享。
@icloud.com #171773 %apple.com

Apple ID 代码为：919426。请勿与他人共享。
@apple.com #919426 %apple.com

**Comment by giaodidii** [comment]
Apple ID 代码为：171773。请勿与他人共享。
@icloud.com #171773 %apple.com

**Comment by AppleIdLoginHelper** [comment]
https://github.com/AppleIdLoginHelper/LoginHelper/commit/97bc10041af917a63bfad1fb493b6e28051f4421

**Comment by ghost** [comment]
> [97bc100](https://github.com/AppleIdLoginHelper/LoginHelper/commit/97bc10041af917a63bfad1fb493b6e28051f4421)

emm看到你更新拉， apple.com的验证码是可以屏蔽拉.  

有没有办法. 屏蔽 设备登录设置icloud的验证码   icloud.com网页的肯定可以实现屏蔽

**Comment by AppleIdLoginHelper** [comment]
https://github.com/AppleIdLoginHelper/LoginHelper/commit/c62262ab1341546ffbba2617a4edb4c593657cc7
