### ISSUE TITLE
如果有人在app store登录了appleid以后没有退出 收不到验证码

### ISSUE THREAD

**Issue by capsule727** [AppleIdLoginHelper/AppleIdLoginHelper#15]
项目很赞，但是遇到个问题， 测试的时候发现。如果有人在app store登录了appleid以后没有退出，别人再登录验证码就不会发到GV的手机号上 会直接发到他的手机设备上显示。 导致GV收不到验证码。有办法解决吗？

**Comment by AppleIdLoginHelper** [comment]
有以下三种方法
- 引导用户遇到这种情况后，点击没有收到验证码，点击发送到xxx（手机号）
- 及时登录 appleid.apple.com 移除这些设备
- 收购apple
