### ISSUE TITLE
请问令牌已经失效怎么重新弄呢？

### ISSUE THREAD

**Issue by c55kai** [AppleIdLoginHelper/AppleIdLoginHelper#17]
打开网页提示：
Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
"error": "invalid_grant",
"error_description": "Token has been expired or revoked."
}
如图：
[https://pic2.58cdn.com.cn/nowater/webim/big/n_v28da46a7de2ca4d6c87d878590ea035cd.png](https://pic2.58cdn.com.cn/nowater/webim/big/n_v28da46a7de2ca4d6c87d878590ea035cd.png)

**Comment by AppleIdLoginHelper** [comment]
gcp控制台发布成正式应用，然后删掉网站目录下的token.json，并重新运行 php quickstart.php 获取授权，就可以一直使用了

qwetrz007sh ***@***.***>于2022年2月27日 周日上午11:11写道：

**Comment by c55kai** [comment]
感谢大佬，可以考虑开通一个捐赠通道

**Comment by qwetrz007sh** [comment]
> 
大佬，没有在目录找到token.json这个文件，具体在哪呢

**Comment by qwetrz007sh** [comment]
我重新建了个OAuth 客户端已，搞好了，好像是删除credentials.json？？
