### ISSUE TITLE
這樣有個問題，用戶可以通過網頁+驗證碼登入，然後修改appleid和密碼

### ISSUE THREAD

**Issue by F5zok3uWc** [AppleIdLoginHelper/AppleIdLoginHelper#2]
這樣有個問題，用戶可以通過網頁+驗證碼登入，然後修改appleid和密碼
不知道有沒有辦法解決

**Comment by AppleIdLoginHelper** [comment]
由于apple发送的验证码短信的内容中不包含对操作的描述，因此不能分辨是在网页登陆时触发的，还是在ios设备上登录时触发的，所以做不到拦截网页登陆时触发的验证码，故此问题无解

**Comment by F5zok3uWc** [comment]
>

**Comment by AppleIdLoginHelper** [comment]
更新到最新 `commit`，然后添加如下内容到 `.env`
```
[OTHER]
AUTO_REFRESH = false
REFRESH_INTERVAL = 5
BLOCK_WEBSITE_LOGIN = false
```
- `AUTO_REFRESH` 网页自动刷新开关，开启需改为 `true`
- `REFRESH_INTERVAL` 如果开启网页自动刷新，则每隔几秒刷新一次
- `BLOCK_WEBSITE_LOGIN` 是否拦截官网登录验证码（appleid.apple.com），开启需改为 `true`
