### ISSUE TITLE
首页好像只显示最新的10个验证码。如果想增加显示的个数，请问该改哪个文件？

### ISSUE THREAD

**Issue by yangyzp** [AppleIdLoginHelper/AppleIdLoginHelper#3]
首页好像只显示最新的10个验证码。如果想增加显示的个数，请问该改哪个文件？谢谢

**Comment by AppleIdLoginHelper** [comment]
https://github.com/AppleIdLoginHelper/LoginHelper/blob/3531f96e994064572e82a4d94efcd61b7e2fd15d/app/controller/Index.php#L105
