### ISSUE TITLE
APi地址又变了吗？网站收不到信息了

### ISSUE THREAD

**Issue by chrisvorer6** [AppleIdLoginHelper/AppleIdLoginHelper#37]
如题，有大佬帮忙解决下不

**Comment by JohnFreeman9** [comment]
Try this commit: [fix: follow apple's new mail detail](https://github.com/JohnFreeman9/LoginHelper/commit/b26def87eed5a02bef4fbf39405df185184018f9)

**Comment by chrisvorer6** [comment]
> Try this commit: [fix: follow apple's new mail detail](https://github.com/JohnFreeman9/LoginHelper/commit/b26def87eed5a02bef4fbf39405df185184018f9)

感谢大佬，可以收到了
