### ISSUE TITLE
真滴棒 这个项目~

### ISSUE THREAD

**Issue by husangou** [AppleIdLoginHelper/AppleIdLoginHelper#4]
最近被弱智客户搞的半天都在解二次验证，不过话说大佬 改账号主体和密码真的没法防吗？最近被搞的有点头大

**Comment by AppleIdLoginHelper** [comment]
https://github.com/AppleIdLoginHelper/LoginHelper/issues/2#issuecomment-1032678658

**Comment by AppleIdLoginHelper** [comment]
更新到最新 `commit`，然后添加如下内容到 `.env`
```
[OTHER]
AUTO_REFRESH = false
REFRESH_INTERVAL = 5
BLOCK_WEBSITE_LOGIN = false
```
- `AUTO_REFRESH` 网页自动刷新开关，开启需改为 `true`
- `REFRESH_INTERVAL` 如果开启网页自动刷新，则每隔几秒刷新一次
- `BLOCK_WEBSITE_LOGIN` 是否拦截官网登录验证码（appleid.apple.com），开启需改为 `true`
