### ISSUE TITLE
其实可以区分设备登陆还是网页登陆的。看看能不能过滤下短信

### ISSUE THREAD

**Issue by 4kercc** [AppleIdLoginHelper/AppleIdLoginHelper#5]
其实是有特征的，具体在下面：

网页登陆：

`Apple ID 代码为：169857。请勿与他人共享。
@apple.com #169857 %apple.com`

设备登陆：

`Apple ID 代码为：556478。请勿与他人共享。`

网页登陆会带上网址后缀，设备上不会出现，我看了代码：
`        $list = $httpClient->get('https://gmail.googleapis.com/gmail/v1/users/'.$email_address.'/messages?maxResults=10&q=from: txt.voice.google.com Apple ID');`

应该是过滤了包含Apple ID的短信才会出现，看看能不能写个黑名单，若短信里面出现 `@apple.com` 或者`%apple.com`，就不接收。

**Comment by giaodidii** [comment]
要是可以区分登录icloud,登录官网,登录app store等验证码。

**Comment by giaodidii** [comment]
只接收app store的验证码就好了。

**Comment by giaodidii** [comment]
进入一个死循环

**Comment by ghost** [comment]
测试 登录苹果商店 苹果官网 设备里登录icloud 三种验证码  其中唯独苹果官网发送的短信中,会有apple.com字样区别，苹果商店以及设备中登录icloud的两种验证码 一模一样 没有任何区别。 也就是意味着,设备登录icloud一样可以对这个id进行任意操作。跟苹果官网如出一辙，所以这个功能可以不用去考虑了。

**Comment by yangyzp** [comment]
能过滤掉登录网页也不错。
因为有些用户登录App Store的时候，不退出自己账号，点进去登录网页界面了。

之前没有这个项目的时候，就有用户过来问我要安全问题，截图一看，他跑到登录网页界面去了。

**Comment by ghost** [comment]
> 能过滤掉登录网页也不错。 因为有些用户登录App Store的时候，不退出自己账号，点进去登录网页界面了。
> 
> 之前没有这个项目的时候，就有用户过来问我要安全问题，截图一看，他跑到登录网页界面去了。

貌似商店 进去后那儿那个二次验证页面 貌似验证码跟官网的不一样的

**Comment by yangyzp** [comment]
> > 能过滤掉登录网页也不错。 因为有些用户登录App Store的时候，不退出自己账号，点进去登录网页界面了。
> > 之前没有这个项目的时候，就有用户过来问我要安全问题，截图一看，他跑到登录网页界面去了。
> 
> 貌似商店 进去后那儿那个二次验证页面 貌似验证码跟官网的不一样的

App Store里面，点击账号（有些小白误操作，没退出原来自己的账号，直接点击账号那）。就会直接跳appid的官网，他以为是登录App Store，其实变成的登录appid的官网（appleid.apple.com）了。

这个时候就是appid的官网验证码。一样的。

**Comment by yangyzp** [comment]
所有还是有必要过来一下官网的验证码的。就想LZ提示的那样，过滤官网发送的验证码的关键词

**Comment by ghost** [comment]
> 所有还是有必要过来一下官网的验证码的。就想LZ提示的那样，过滤官网发送的验证码的关键词

这个倒是没错，现在有个非常恶心的问题，苹果的机制就是开了双重，登录官网不用回答三个问题，太操蛋了。包括设备登录icloud也可以对账号进行操作。难搞，共享ID越来越恶心了这苹果机制

**Comment by yangyzp** [comment]
> > 所有还是有必要过来一下官网的验证码的。就想LZ提示的那样，过滤官网发送的验证码的关键词
> 
> 这个倒是没错，现在有个非常恶心的问题，苹果的机制就是开了双重，登录官网不用回答三个问题，太操蛋了。包括设备登录icloud也可以对账号进行操作。难搞，共享ID越来越恶心了这苹果机制

这个确实。现在只能说，尽量减少用完误操作登录网页的情况。

**Comment by xinan1212** [comment]
打电话关闭开启双重的步骤，即可解决所有烦恼

**Comment by AppleIdLoginHelper** [comment]
更新到最新 `commit`，然后添加如下内容到 `.env`
```
[OTHER]
AUTO_REFRESH = false
REFRESH_INTERVAL = 5
BLOCK_WEBSITE_LOGIN = false
```
- `AUTO_REFRESH` 网页自动刷新开关，开启需改为 `true`
- `REFRESH_INTERVAL` 如果开启网页自动刷新，则每隔几秒刷新一次
- `BLOCK_WEBSITE_LOGIN` 是否拦截官网登录验证码（appleid.apple.com），开启需改为 `true`
