### ISSUE TITLE
账户名称显示 unknow

### ISSUE THREAD

**Issue by ghost** [AppleIdLoginHelper/AppleIdLoginHelper#6]
![微信截图_20220209113244](https://user-images.githubusercontent.com/98938205/153116870-a5ae7161-0dc2-4dda-bd15-1720d8b29f9f.png)
![微信截图_20220209113307](https://user-images.githubusercontent.com/98938205/153116881-bed84b38-ec29-4073-b6ec-304d9a9bc8c8.png)
重新搭建了一遍 账户名称显示 unknow

**Comment by AppleIdLoginHelper** [comment]
看注释

**Comment by ghost** [comment]
找到原因了 google api 程序 OAuth 同意屏幕这里选错了（非测试版）就会造成 账号unknow
