### ISSUE TITLE
一直显示invalid token

### ISSUE THREAD

**Issue by hsly109** [AppleIdLoginHelper/AppleIdLoginHelper#8]
Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
"error": "invalid_grant",
"error_description": "Token has been expired or revoked."
}

反复重建了2次换了2个不同的google voice账号建api都这样

**Comment by AppleIdLoginHelper** [comment]
rm -rf token.json
php quickstart.php

反正不是我代码的问题
