### ISSUE TITLE
复制生成的链接与不一样

### ISSUE THREAD

**Issue by JusufUs** [AppleIdLoginHelper/AppleIdLoginHelper#9]
检查过填写的auto都正确的，唯独不同的是我生成连接下面会有一个Enter verification code: 

打开连接然后会返回到网站，显示的内容是：
callback

复制下方的字符串，返回 ssh 软件，粘贴并按下回车

4/0AX4XfWguDNCEZckMTTJOwgd2yAVm0BL3ddADnPEkYh7ZXkpfs14f1d-fdhbbf

**Comment by AppleIdLoginHelper** [comment]
有什么问题么，根据提示操作即可

JusufUs ***@***.***>于2022年2月11日 周五下午5:21写道：

**Comment by JusufUs** [comment]
没有问题，我脑子瓦特了
